### PR TITLE
DND 5e API Viewer

### PR DESCRIPTION
**Pull request by RokoVarano**
This aplication will allow you to see the contents of the DnD5E API (http://www.dnd5eapi.co/) on your screen.

- In the main page, use the input bar at the top and click on the grey eye button at the top right to filter your categories.
Clear the input to get the full list.
- Click on a category square to go into it's submenu.
- In the submenu, click an item to get into the details.
- To go to the previous page from anywhere, click on the '<' button at the top left, in the header.

Video is still not available. It will be when the rest of the project has been approved. 
Thanks for your review!

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Please follow the given [design ](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs))layout. This is a basic requirement of this project. Your design looks like this: 
a

- [ ] Uses a Filter stateless component to filter data retrieved from the API. I can see you have added a filter but that is not working on my side. 
- [ ] The video you created should contain a highlight about a piece of the code you find interesting or proud of making.

> 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by RokoVarano** [comment]
Hi! I have some questions regarding your review.

> * [ ]  Please follow the given [design ](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs))layout. This is a basic requirement of this project.

Could you explain please? in your picture, you are showing the full website view, but the requirements are for mobile view. Of course, this is going to make the fonts look very small in comparison. Is that what you mean?
The original design has no filter. Where should I put it to follow it?
I do agree that the colors in the options are not alternate like in the original design.

> * [ ]  Uses a Filter stateless component to filter data retrieved from the API. I can see you have added a filter but that is not working on my side.

This works both in the live server (Netlify)  and locally. Could you please send the error you get in the console (if any) to check what the problem is?

> * [ ]  The video you created should contain a highlight about a piece of the code you find interesting or proud of making.

I have not done the video yet as I explained in the Readme, so this is ok, I'll do it as soon as the rest of the project is approved.

Thanks for your answer in advance.

**Comment by arslanbisharat** [comment]
> Hi! I have some questions regarding your review.
> 
> > * [ ]   Please follow the given [design ](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs))layout. This is a basic requirement of this project.
> 
> Could you explain please? in your picture, you are showing the full website view, but the requirements are for mobile view. Of course, this is going to make the fonts look very small in comparison. Is that what you mean?
> The original design has no filter. Where should I put it to follow it?
> I do agree that the colors in the options are not alternate like in the original design.
> 
> > * [ ]   Uses a Filter stateless component to filter data retrieved from the API. I can see you have added a filter but that is not working on my side.
> 
> This works both in the live server (Netlify) and locally. Could you please send the error you get in the console (if any) to check what the problem is?
> 
> > * [ ]   The video you created should contain a highlight about a piece of the code you find interesting or proud of making.
> 
> I have not done the video yet as I explained in the Readme, so this is ok, I'll do it as soon as the rest of the project is approved.
> 
> Thanks for your answer in advance.
The project is for web not mobile so you are required to work on the given design. 

You need to create video before requesting another review otherwise your project won't get approved even you worked on other changes

**Comment by RokoVarano** [comment]
> > Hi! I have some questions regarding your review.
> > > * [ ]    Please follow the given [design ](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs))layout. This is a basic requirement of this project.
> > 
> > 
> > Could you explain please? in your picture, you are showing the full website view, but the requirements are for mobile view. Of course, this is going to make the fonts look very small in comparison. Is that what you mean?
> > The original design has no filter. Where should I put it to follow it?
> > I do agree that the colors in the options are not alternate like in the original design.
> > > * [ ]    Uses a Filter stateless component to filter data retrieved from the API. I can see you have added a filter but that is not working on my side.
> > 
> > 
> > This works both in the live server (Netlify) and locally. Could you please send the error you get in the console (if any) to check what the problem is?
> > > * [ ]    The video you created should contain a highlight about a piece of the code you find interesting or proud of making.
> > 
> > 
> > I have not done the video yet as I explained in the Readme, so this is ok, I'll do it as soon as the rest of the project is approved.
> > Thanks for your answer in advance.
> > The project is for web not mobile so you are required to work on the given design.
> 
> You need to create video before requesting another review otherwise your project won't get approved even you worked on other changes

Yes, I understand this. What about the other questions?

**Comment by RokoVarano** [comment]
To the next TSE:
Please give details of what is wrong with this project (other than the absence of the video) to make the necessary changes. If it does not work on your end, please take a screenshot of the error, if any.

Please remember this project is scaled for mobile versions, as per the requirements.

**Comment by RokoVarano** [comment]
Video presentation included. Check it here: https://www.loom.com/share/77a26898680341bfa20b7b7610d42d8b

**Review by oloomoses — APPROVED** [review]
Hi @RokoVarano, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
